// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEVOQLhJrPsO6gblc4Uye_bPI9h_8_97U',
    appId: '1:439756342038:web:7324fd8392224409dcc637',
    messagingSenderId: '439756342038',
    projectId: 'fitnessaut',
    authDomain: 'fitnessaut.firebaseapp.com',
    storageBucket: 'fitnessaut.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWvH8vHoAAPLrchMuzsFYweLorNH5wTKE',
    appId: '1:439756342038:android:303c8e2b2c4f4d43dcc637',
    messagingSenderId: '439756342038',
    projectId: 'fitnessaut',
    storageBucket: 'fitnessaut.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApg0yBscikCU6ejPhhC4mEu-DcuZttHQU',
    appId: '1:439756342038:ios:2a65cf07c3e36020dcc637',
    messagingSenderId: '439756342038',
    projectId: 'fitnessaut',
    storageBucket: 'fitnessaut.firebasestorage.app',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApg0yBscikCU6ejPhhC4mEu-DcuZttHQU',
    appId: '1:439756342038:ios:2a65cf07c3e36020dcc637',
    messagingSenderId: '439756342038',
    projectId: 'fitnessaut',
    storageBucket: 'fitnessaut.firebasestorage.app',
    iosBundleId: 'com.example.projectName',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEVOQLhJrPsO6gblc4Uye_bPI9h_8_97U',
    appId: '1:439756342038:web:835414df717ae1fadcc637',
    messagingSenderId: '439756342038',
    projectId: 'fitnessaut',
    authDomain: 'fitnessaut.firebaseapp.com',
    storageBucket: 'fitnessaut.firebasestorage.app',
  );
}
