import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:image_picker/image_picker.dart';
import 'dart:io';
import '../../core/theme.dart';
import '../../core/sky_widgets.dart';
import '../../models/complaint.dart';
import '../../providers/auth_provider.dart';
import '../../providers/complaint_provider.dart';

class AddComplaintScreen extends StatefulWidget {
  const AddComplaintScreen({super.key});

  @override
  State<AddComplaintScreen> createState() => _AddComplaintScreenState();
}

class _AddComplaintScreenState extends State<AddComplaintScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _descriptionController = TextEditingController();
  
  ComplaintCategory _selectedCategory = ComplaintCategory.plumbing;
  UrgencyLevel _selectedUrgency = UrgencyLevel.medium;
  File? _imageFile;
  final ImagePicker _picker = ImagePicker();
  bool _isSubmitting = false;

  Future<void> _pickImage() async {
    final XFile? pickedFile = await _picker.pickImage(source: ImageSource.gallery);
    if (pickedFile != null) {
      setState(() {
        _imageFile = File(pickedFile.path);
      });
    }
  }

  void _submitComplaint() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isSubmitting = true);
      
      try {
        final user = Provider.of<AuthProvider>(context, listen: false).currentUser;
        if (user == null) throw Exception('User not logged in');

        final newComplaint = Complaint(
          id: '', // Generated by DB
          title: _titleController.text,
          description: _descriptionController.text,
          category: _selectedCategory,
          urgency: _selectedUrgency,
          studentId: user.id,
          studentName: user.name,
          roomNumber: user.roomNumber ?? 'N/A',
          createdAt: DateTime.now(),
        );

        await Provider.of<ComplaintProvider>(context, listen: false).addComplaint(newComplaint);
        
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Complaint submitted successfully'), backgroundColor: AppTheme.success),
          );
          _titleController.clear();
          _descriptionController.clear();
          setState(() {
             _imageFile = null;
          });
        }
      } catch (e) {
        if (mounted) {
           ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e'), backgroundColor: AppTheme.error));
        }
      } finally {
        if (mounted) setState(() => _isSubmitting = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: AppBar(title: const Text('New Complaint'), backgroundColor: Colors.transparent),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              GlassCard(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    const Text('Title', style: TextStyle(fontWeight: FontWeight.bold)),
                    const SizedBox(height: 8),
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(hintText: 'e.g., Leaking tap'),
                      validator: (val) => val!.isEmpty ? 'Required' : null,
                    ),
                    const SizedBox(height: 20),
                    
                    const Text('Category', style: TextStyle(fontWeight: FontWeight.bold)),
                    const SizedBox(height: 8),
                    Wrap(
                      spacing: 8,
                      children: ComplaintCategory.values.map((cat) {
                        final isSelected = _selectedCategory == cat;
                        return ChoiceChip(
                          label: Text(cat.name.toUpperCase()),
                          selected: isSelected,
                          onSelected: (val) => setState(() => _selectedCategory = cat),
                          selectedColor: AppTheme.lightBlue,
                          labelStyle: TextStyle(
                            color: isSelected ? AppTheme.primaryBlue : AppTheme.textSecondary,
                            fontWeight: isSelected ? FontWeight.bold : FontWeight.normal
                          ),
                          backgroundColor: Colors.white,
                        );
                      }).toList(),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 20),

              GlassCard(
                child: Column(
                   crossAxisAlignment: CrossAxisAlignment.start,
                   children: [
                     const Text('Details', style: TextStyle(fontWeight: FontWeight.bold)),
                     const SizedBox(height: 8),
                     TextFormField(
                       controller: _descriptionController,
                       maxLines: 4,
                        decoration: const InputDecoration(hintText: 'Describe the issue...'),
                        validator: (val) => val!.isEmpty ? 'Required' : null,
                     ),
                     const SizedBox(height: 16),
                     GestureDetector(
                       onTap: _pickImage,
                       child: Container(
                         padding: const EdgeInsets.symmetric(vertical: 12),
                         decoration: BoxDecoration(
                           border: Border.all(color: AppTheme.primaryBlue.withValues(alpha: 0.5), style: BorderStyle.solid),
                           borderRadius: BorderRadius.circular(12),
                           color: AppTheme.lightBlue.withValues(alpha: 0.3),
                         ),
                         child: Row(
                           mainAxisAlignment: MainAxisAlignment.center,
                           children: [
                             Icon(Icons.camera_alt, color: AppTheme.primaryBlue),
                             const SizedBox(width: 8),
                             Text(
                               _imageFile != null ? 'Image Selected' : 'Attach Photo',
                               style: TextStyle(color: AppTheme.primaryBlue, fontWeight: FontWeight.bold),
                             ),
                           ],
                         ),
                       ),
                     ),
                     if (_imageFile != null)
                        Padding(
                          padding: const EdgeInsets.only(top: 8),
                          child: Text(_imageFile!.path.split('/').last, style: const TextStyle(fontSize: 12, color: Colors.grey)),
                        ),
                   ],
                ),
              ),

              const SizedBox(height: 32),
              ElevatedButton(
                onPressed: _isSubmitting ? null : _submitComplaint,
                child: _isSubmitting ? const CircularProgressIndicator(color: Colors.white) : const Text('Submit Complaint'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
