// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNgrrNhJIqyiUos_9iLEKflblTp-PbeuA',
    appId: '1:1016172854056:web:9a615e61a10f4e88e5ae1d',
    messagingSenderId: '1016172854056',
    projectId: 'cooklogin',
    authDomain: 'cooklogin.firebaseapp.com',
    storageBucket: 'cooklogin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbE7lHptWyvdYOgXry6woETRBlLr0epIo',
    appId: '1:1016172854056:android:c8a461a99b59e2d0e5ae1d',
    messagingSenderId: '1016172854056',
    projectId: 'cooklogin',
    storageBucket: 'cooklogin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCz0iVsqHojJ3jei_FK81dlL57XhAOdmM',
    appId: '1:1016172854056:ios:1f0f785a0038b3d9e5ae1d',
    messagingSenderId: '1016172854056',
    projectId: 'cooklogin',
    storageBucket: 'cooklogin.firebasestorage.app',
    iosClientId: '1016172854056-h1f9kipfjt2pkk4tpvo07vj5n8te2sj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCz0iVsqHojJ3jei_FK81dlL57XhAOdmM',
    appId: '1:1016172854056:ios:1f0f785a0038b3d9e5ae1d',
    messagingSenderId: '1016172854056',
    projectId: 'cooklogin',
    storageBucket: 'cooklogin.firebasestorage.app',
    iosClientId: '1016172854056-h1f9kipfjt2pkk4tpvo07vj5n8te2sj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNgrrNhJIqyiUos_9iLEKflblTp-PbeuA',
    appId: '1:1016172854056:web:8dd9608949050a9ee5ae1d',
    messagingSenderId: '1016172854056',
    projectId: 'cooklogin',
    authDomain: 'cooklogin.firebaseapp.com',
    storageBucket: 'cooklogin.firebasestorage.app',
  );
}
